'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/themeprovider";
import UserContext from "@/components/ui/usercontext";
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>BlogBaan</title>
      </head>
      <body className={inter.className}>
        <UserContext>

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>

              <ProgressBar
              color="yellow"
              options={{showSpinner:false}}
              height="4px"
              />

        {children}

        </ThemeProvider>

              </UserContext>
        </body>
    </html>
  );
}
